# Generated by Django 5.1.3 on 2024-11-27 08:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=50, unique=True)),
                ('color_1', models.CharField(default='', max_length=10)),
                ('color_2', models.CharField(default='', max_length=10)),
                ('color_3', models.CharField(default='', max_length=10)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
