# Generated by Django 5.1.3 on 2024-11-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='color_1',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='color_2',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='color_3',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='colors',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='host',
            field=models.CharField(max_length=50),
        ),
    ]
