# Generated by Django 5.1.3 on 2024-11-28 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_searchquery_color_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='host',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField()),
                ('image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.searchquery')),
            ],
        ),
    ]
