# Generated by Django 5.1.3 on 2024-11-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_listing_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QueryMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listing')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.searchquery')),
            ],
        ),
    ]
