# Generated by Django 5.1.3 on 2024-11-30 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_searchquery_completed_querymatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='querymatch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
