# Generated by Django 5.1.3 on 2024-11-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_listing_created_at_alter_querymatch_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='colors',
            field=models.CharField(default='', max_length=200),
        ),
    ]
