# Generated by Django 5.1.3 on 2024-11-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_listing_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='url',
        ),
        migrations.AddField(
            model_name='listing',
            name='color_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='retailer_image_url',
            field=models.URLField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='listing',
            name='retailer_url',
            field=models.URLField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
