# Generated by Django 5.1.3 on 2024-11-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_listing_url_listing_color_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='solid_color',
            field=models.BooleanField(default=False),
        ),
    ]
