# Generated by Django 5.1.3 on 2024-11-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_listing_solid_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='colors',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='retailer_url',
            field=models.URLField(max_length=2000),
        ),
    ]
